#!/usr/bin/python2

#
# MapInfo - Extract scripts of Wild Arms maps
#
# Copyright (C) Christian Bauer <www.cebix.net>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#

__version__ = "1.0"

import sys
import os
import struct
import shutil
import codecs
import locale

sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout, "backslashreplace")
sys.stderr = codecs.getwriter(locale.getpreferredencoding())(sys.stderr, "backslashreplace")

import wa
from wa.map import Op


# Print usage information and exit.
def usage(exitcode, error = None):
    print "Usage: %s [OPTION...] <game_dir_or_image> <output_dir>" % os.path.basename(sys.argv[0])
    print "  -V, --version                   Display version information and exit"
    print "  -?, --help                      Show this help message"

    if error is not None:
        print >>sys.stderr, "\nError:", error

    sys.exit(exitcode)


# Parse command line arguments
gamePath = None
outputDir = None

for arg in sys.argv[1:]:
    if arg == "--version" or arg == "-V":
        print "MapInfo", __version__
        sys.exit(0)
    elif arg == "--help" or arg == "-?":
        usage(0)
    elif arg[0] == "-":
        usage(64, "Invalid option '%s'" % arg)
    else:
        if gamePath is None:
            gamePath = arg
        elif outputDir is None:
            outputDir = arg
        else:
            usage(64, "Unexpected extra argument '%s'" % arg)

if gamePath is None:
    usage(64, "No disc image or game data input directory specified")
if outputDir is None:
    usage(64, "No output directory specified")

try:

    # Open the input image
    image = wa.openImage(gamePath)

    # Create the output directory
    if os.path.isfile(outputDir):
        print >>sys.stderr, "Cannot create output directory '%s': Path refers to a file" % outputDir
        sys.exit(1)

    if os.path.isdir(outputDir):
        answer = None
        while answer not in ["y", "n"]:
            answer = raw_input("Output directory '%s' exists. Delete and overwrite it (y/n)? " % outputDir)

        if answer == 'y':
            shutil.rmtree(outputDir)
        else:
            sys.exit(0)

    try:
        os.makedirs(outputDir)
    except OSError, e:
        print >>sys.stderr, "Cannot create output directory '%s': %s" % (outputDir, e.strerror)
        sys.exit(1)

    # Retrieve the map file and game executable
    mapFile = image.openFile("BIN", "CDSTG.BIN")

    exeFile = image.openFile("EXE", "WILDARMS.EXE")
    exeData = exeFile.read()

    nameTableOffset = wa.data.mapNameTableOffset(image.version)

    # Process all maps
    for mapNumber in xrange(128):

        # Read the map data block
        block = mapFile.read(0x91000)

        # Map 25 is dummied out
        if mapNumber == 25:
            continue

        print "  map", mapNumber

        # Create the output file
        filePath = os.path.join(outputDir, "map_%03d.txt" % mapNumber)
        try:
            f = open(filePath, "w")
        except IOError, e:
            print >>sys.stderr, "Cannot create file '%s': %s" % (filePath, e.strerror)
            sys.exit(1)

        # Find the map name
        p = struct.unpack_from("<L", exeData, nameTableOffset + mapNumber * 4)[0]
        o = p - 0x80011420 + 0x800
        mapName = wa.text.decode(exeData[o:exeData.index('\0', o)], image.version)

        print >>f, "##"
        print >>f, "## Map number %d (%s)" % (mapNumber, mapName.encode("utf-8"))
        print >>f, "##"
        print >>f

        # Extract the scripts
        mapData = wa.map.MapData(block, mapNumber, image.version)

        entries = []
        entries.append(mapData.getGlobalEntries())
        entries.append(mapData.getScript1Entries())
        entries.append(mapData.getScript2Entries())

        script1 = mapData.getScript1()
        script2 = mapData.getScript2()

        for scriptName, script in [("Script 1", script1), ("Script 2", script2)]:
            print >>f, "#"
            print >>f, "#", scriptName
            print >>f, "#"
            print >>f

            prevLineEmpty = False

            for instr in script:
                haveEntry = False

                for n in xrange(len(entries)):
                    for idx in [i for i, addr in enumerate(entries[n]) if addr == instr.addr]:
                        if not haveEntry and not prevLineEmpty:
                            print >>f

                        print >>f, "Entry %d.%d:" % (n, idx)
                        haveEntry = True
                        prevLineEmpty = False

                if haveEntry:
                    print >>f

                print >>f, "%04x:" % instr.addr, instr.disass.encode("utf-8")

                if instr.op in [Op.RETURN, Op.PTR]:
                    print >>f
                    prevLineEmpty = True

except Exception, e:

    # Pokemon exception handler
    if e.message:
        print >>sys.stderr, e.message
        sys.exit(1)
    else:
        raise
